// Code generated by thriftgo (0.3.2). DO NOT EDIT.

package api

import (
	"context"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"micah.wiki/pandora/kitex_gen/dragon"
)

type Pandora interface {
	DragonSay(ctx context.Context, req *dragon.DragonSayRequest) (r *dragon.DragonSayResponse, err error)
}

type PandoraClient struct {
	c thrift.TClient
}

func NewPandoraClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *PandoraClient {
	return &PandoraClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewPandoraClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *PandoraClient {
	return &PandoraClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewPandoraClient(c thrift.TClient) *PandoraClient {
	return &PandoraClient{
		c: c,
	}
}

func (p *PandoraClient) Client_() thrift.TClient {
	return p.c
}

func (p *PandoraClient) DragonSay(ctx context.Context, req *dragon.DragonSayRequest) (r *dragon.DragonSayResponse, err error) {
	var _args PandoraDragonSayArgs
	_args.Req = req
	var _result PandoraDragonSayResult
	if err = p.Client_().Call(ctx, "dragonSay", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

type PandoraProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      Pandora
}

func (p *PandoraProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *PandoraProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *PandoraProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewPandoraProcessor(handler Pandora) *PandoraProcessor {
	self := &PandoraProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self.AddToProcessorMap("dragonSay", &pandoraProcessorDragonSay{handler: handler})
	return self
}
func (p *PandoraProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}

type pandoraProcessorDragonSay struct {
	handler Pandora
}

func (p *pandoraProcessorDragonSay) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := PandoraDragonSayArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("dragonSay", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := PandoraDragonSayResult{}
	var retval *dragon.DragonSayResponse
	if retval, err2 = p.handler.DragonSay(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing dragonSay: "+err2.Error())
		oprot.WriteMessageBegin("dragonSay", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("dragonSay", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type PandoraDragonSayArgs struct {
	Req *dragon.DragonSayRequest `thrift:"req,1" frugal:"1,default,dragon.DragonSayRequest" json:"req"`
}

func NewPandoraDragonSayArgs() *PandoraDragonSayArgs {
	return &PandoraDragonSayArgs{}
}

func (p *PandoraDragonSayArgs) InitDefault() {
	*p = PandoraDragonSayArgs{}
}

var PandoraDragonSayArgs_Req_DEFAULT *dragon.DragonSayRequest

func (p *PandoraDragonSayArgs) GetReq() (v *dragon.DragonSayRequest) {
	if !p.IsSetReq() {
		return PandoraDragonSayArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PandoraDragonSayArgs) SetReq(val *dragon.DragonSayRequest) {
	p.Req = val
}

var fieldIDToName_PandoraDragonSayArgs = map[int16]string{
	1: "req",
}

func (p *PandoraDragonSayArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PandoraDragonSayArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_PandoraDragonSayArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *PandoraDragonSayArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = dragon.NewDragonSayRequest()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *PandoraDragonSayArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("dragonSay_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *PandoraDragonSayArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *PandoraDragonSayArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PandoraDragonSayArgs(%+v)", *p)
}

func (p *PandoraDragonSayArgs) DeepEqual(ano *PandoraDragonSayArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *PandoraDragonSayArgs) Field1DeepEqual(src *dragon.DragonSayRequest) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

type PandoraDragonSayResult struct {
	Success *dragon.DragonSayResponse `thrift:"success,0,optional" frugal:"0,optional,dragon.DragonSayResponse" json:"success,omitempty"`
}

func NewPandoraDragonSayResult() *PandoraDragonSayResult {
	return &PandoraDragonSayResult{}
}

func (p *PandoraDragonSayResult) InitDefault() {
	*p = PandoraDragonSayResult{}
}

var PandoraDragonSayResult_Success_DEFAULT *dragon.DragonSayResponse

func (p *PandoraDragonSayResult) GetSuccess() (v *dragon.DragonSayResponse) {
	if !p.IsSetSuccess() {
		return PandoraDragonSayResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PandoraDragonSayResult) SetSuccess(x interface{}) {
	p.Success = x.(*dragon.DragonSayResponse)
}

var fieldIDToName_PandoraDragonSayResult = map[int16]string{
	0: "success",
}

func (p *PandoraDragonSayResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PandoraDragonSayResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_PandoraDragonSayResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *PandoraDragonSayResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = dragon.NewDragonSayResponse()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *PandoraDragonSayResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("dragonSay_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *PandoraDragonSayResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *PandoraDragonSayResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PandoraDragonSayResult(%+v)", *p)
}

func (p *PandoraDragonSayResult) DeepEqual(ano *PandoraDragonSayResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *PandoraDragonSayResult) Field0DeepEqual(src *dragon.DragonSayResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
