// Code generated by Kitex v0.7.3. DO NOT EDIT.

package pandora

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "micah.wiki/pandora/kitex_gen/api"
	dragon "micah.wiki/pandora/kitex_gen/dragon"
)

func serviceInfo() *kitex.ServiceInfo {
	return pandoraServiceInfo
}

var pandoraServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "Pandora"
	handlerType := (*api.Pandora)(nil)
	methods := map[string]kitex.MethodInfo{
		"dragonSay": kitex.NewMethodInfo(dragonSayHandler, newPandoraDragonSayArgs, newPandoraDragonSayResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "api",
		"ServiceFilePath": `thrift/pandora_service.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.7.3",
		Extra:           extra,
	}
	return svcInfo
}

func dragonSayHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.PandoraDragonSayArgs)
	realResult := result.(*api.PandoraDragonSayResult)
	success, err := handler.(api.Pandora).DragonSay(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPandoraDragonSayArgs() interface{} {
	return api.NewPandoraDragonSayArgs()
}

func newPandoraDragonSayResult() interface{} {
	return api.NewPandoraDragonSayResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) DragonSay(ctx context.Context, req *dragon.DragonSayRequest) (r *dragon.DragonSayResponse, err error) {
	var _args api.PandoraDragonSayArgs
	_args.Req = req
	var _result api.PandoraDragonSayResult
	if err = p.c.Call(ctx, "dragonSay", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
