// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysMenu = "sys_menu"

// SysMenu mapped from table <sys_menu>
type SysMenu struct {
	MenuID     int64      `gorm:"column:menu_id;type:bigint;primaryKey;autoIncrement:true;comment:菜单ID" json:"menu_id"` // 菜单ID
	MenuName   string     `gorm:"column:menu_name;type:varchar(50);not null;comment:菜单名称" json:"menu_name"`             // 菜单名称
	ParentID   *int64     `gorm:"column:parent_id;type:bigint;comment:父菜单ID" json:"parent_id"`                          // 父菜单ID
	OrderNum   *int64     `gorm:"column:order_num;type:int;comment:显示顺序" json:"order_num"`                              // 显示顺序
	Path       *string    `gorm:"column:path;type:varchar(200);comment:路由地址" json:"path"`                               // 路由地址
	Component  *string    `gorm:"column:component;type:varchar(255);comment:组件路径" json:"component"`                     // 组件路径
	Query      *string    `gorm:"column:query;type:varchar(255);comment:路由参数" json:"query"`                             // 路由参数
	IsFrame    *int64     `gorm:"column:is_frame;type:int;default:1;comment:是否为外链（0是 1否）" json:"is_frame"`              // 是否为外链（0是 1否）
	IsCache    *int64     `gorm:"column:is_cache;type:int;comment:是否缓存（0缓存 1不缓存）" json:"is_cache"`                      // 是否缓存（0缓存 1不缓存）
	MenuType   *string    `gorm:"column:menu_type;type:char(1);comment:菜单类型（M目录 C菜单 F按钮）" json:"menu_type"`             // 菜单类型（M目录 C菜单 F按钮）
	Visible    *string    `gorm:"column:visible;type:char(1);default:0;comment:菜单状态（0显示 1隐藏）" json:"visible"`           // 菜单状态（0显示 1隐藏）
	Status     *string    `gorm:"column:status;type:char(1);default:0;comment:菜单状态（0正常 1停用）" json:"status"`             // 菜单状态（0正常 1停用）
	Perms      *string    `gorm:"column:perms;type:varchar(100);comment:权限标识" json:"perms"`                             // 权限标识
	Icon       *string    `gorm:"column:icon;type:varchar(100);default:#;comment:菜单图标" json:"icon"`                     // 菜单图标
	CreateBy   *string    `gorm:"column:create_by;type:varchar(64);comment:创建者" json:"create_by"`                       // 创建者
	CreateTime *time.Time `gorm:"column:create_time;type:datetime;comment:创建时间" json:"create_time"`                     // 创建时间
	UpdateBy   *string    `gorm:"column:update_by;type:varchar(64);comment:更新者" json:"update_by"`                       // 更新者
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime;comment:更新时间" json:"update_time"`                     // 更新时间
	Remark     *string    `gorm:"column:remark;type:varchar(500);comment:备注" json:"remark"`                             // 备注
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
